### ISSUE TITLE
ApiError: res['errors'] throws when res is null

### ISSUE THREAD

**Issue by kozak** [mailjet/mailjet-gem#127]
We are getting: 
```
undefined method []' for nil:NilClass
mailjet-1.4.12/lib/mailjet/api_error.rb:19:in 'initialize'
```

The check if `res.nil?` happens before decoding the json, but then you you try to retrieve res['errors'] even if `res` doesn't exist.

**Comment by Lorel** [comment]
indeed @kozak, there is a bug here
it should be fixed by #133 
thx

**Comment by zyqxd** [comment]
Is there a plan to releasing this outside of master? Latest tag (1.5.4) still has this issue

**Comment by Ikaarou** [comment]
> Is there a plan to releasing this outside of master? Latest tag (1.5.4) still has this issue

This error is still present as of June 2020. Any plans to make it available ?
